In [1]:
uimport numpy as np
import cv2 as cv

# Image Read

In [2]:
img = cv.imread("animal.jpg")

In [3]:
img

array([[[249, 236, 190],
        [231, 180,   0],
        [231, 180,   0],
        ...,
        [231, 180,   0],
        [231, 180,   0],
        [255, 255, 255]],

       [[249, 236, 190],
        [231, 180,   0],
        [231, 180,   0],
        ...,
        [231, 180,   0],
        [231, 180,   0],
        [255, 255, 255]],

       [[249, 236, 190],
        [231, 180,   0],
        [231, 180,   0],
        ...,
        [231, 180,   0],
        [231, 180,   0],
        [255, 255, 255]],

       ...,

       [[215, 239, 231],
        [ 90, 190, 162],
        [ 88, 190, 162],
        ...,
        [115, 211, 200],
        [115, 212, 198],
        [255, 255, 255]],

       [[219, 243, 241],
        [116, 213, 199],
        [115, 212, 198],
        ...,
        [115, 212, 198],
        [117, 212, 198],
        [255, 255, 254]],

       [[220, 246, 240],
        [115, 211, 200],
        [115, 212, 198],
        ...,
        [ 79, 183, 148],
        [ 90, 189, 163],
        [255, 255, 255]]

Image Show

In [4]:
cv.imshow("Original Image",img)
cv.waitKey(0)         #waitkey is so that loaded image stays on screen
cv.destroyAllWindows()       # we have to close this image or program will no go forward 

# Image Resize

In [5]:
re_img = cv.resize(img, (200, 200))

In [43]:
cv.imwrite(r"D:\Data Science Program\AI\Image Augumented\resized_img.jpg",re_img)
cv.imshow("Resized Image",re_img)   # It can change the size of image
cv.waitKey(0)         
cv.destroyAllWindows() 

# Image Color Channel

In [7]:
red = re_img.copy()

In [8]:
red.shape

(200, 200, 3)

In [9]:
red[:,:,[0,1]] = 0

In [44]:
cv.imwrite(r"D:\Data Science Program\AI\Image Augumented\red_img.jpg",red)
cv.imshow("Red Image", red)  #It use for change the colour of image on red
cv.waitKey(0)
cv.destroyAllWindows()

In [11]:
green = re_img.copy()

In [12]:
green[:,:,[0,2]]= 0

In [45]:
cv.imwrite(r"D:\Data Science Program\AI\Image Augumented\green_img.jpg",green)
cv.imshow("Green Image", green)  #It use for change the colour of image on green
cv.waitKey(0)
cv.destroyAllWindows()

In [14]:
blue = re_img.copy()

In [15]:
blue[:,:,[1,2]]= 0

In [46]:
cv.imwrite(r"D:\Data Science Program\AI\Image Augumented\blue_img.jpg",blue)
cv.imshow("Blue Image", blue)  #It use for change the colour of image on blue
cv.waitKey(0)
cv.destroyAllWindows()

In [17]:
cv.imshow("Addition of all color channel",(blue + green + red)) 
cv.waitKey(0)
cv.destroyAllWindows()

In [18]:
arr = np.random.randint(0, 255, 36).reshape(3,4,3)

In [19]:
arr

array([[[131,  69,  10],
        [135,  39, 155],
        [204, 109, 183],
        [ 54, 241, 237]],

       [[ 86,  88, 238],
        [178,  80, 171],
        [119,  70,  33],
        [241,  89, 172]],

       [[ 75,  62,   2],
        [ 59,  68, 100],
        [229, 159,  23],
        [119, 142, 249]]], dtype=int32)

In [20]:
arr.shape

(3, 4, 3)

In [21]:
arr[:,:,[0,1]] = 0
arr

array([[[  0,   0,  10],
        [  0,   0, 155],
        [  0,   0, 183],
        [  0,   0, 237]],

       [[  0,   0, 238],
        [  0,   0, 171],
        [  0,   0,  33],
        [  0,   0, 172]],

       [[  0,   0,   2],
        [  0,   0, 100],
        [  0,   0,  23],
        [  0,   0, 249]]], dtype=int32)

# Image Color to grayscale

In [22]:
gray_img = cv.cvtColor(re_img, cv.COLOR_BGR2GRAY)

In [47]:
cv.imwrite(r"D:\Data Science Program\AI\Image Augumented\gray_img.jpg",gray_img)
cv.imshow("Gray Image", gray_img)  
cv.waitKey(0)
cv.destroyAllWindows()

# Adding Blur to Image

In [24]:
blur_img1 = cv.GaussianBlur(re_img,(3,3), 2)  #gaussian its just scientist name
blur_img2 = cv.GaussianBlur(re_img, (5,5), 6)  #it can adding two images 

In [25]:
two_img = np.hstack((blur_img1, blur_img2))

In [48]:
cv.imwrite(r"D:\Data Science Program\AI\Image Augumented\two_img.jpg",two_img)
cv.imshow("Blur Images", two_img) 
cv.waitKey(0)
cv.destroyAllWindows()

# Edge Detction in Image

In [27]:
edges1 = cv.Canny(gray_img,100, 200)
edges2 = cv.Canny(gray_img, 150, 300)

In [28]:
two_edges = np.hstack((edges1,edges2))

In [49]:
cv.imwrite(r"D:\Data Science Program\AI\Image Augumented\two_edges.jpg",two_edges)
cv.imshow("Edges of Images", two_edges)
cv.waitKey(0)
cv.destroyAllWindows()

# Rotate Image

In [30]:
angle = 60
rows, cols = re_img.shape[:2]   ##Rows means width and cols means Height
center = (cols//2, rows//2)

In [31]:
center

(100, 100)

In [32]:
rotate_mat = cv.getRotationMatrix2D(center, angle, scale=0.8)

In [33]:
rotate_img = cv.warpAffine(re_img, rotate_mat, (cols, rows)) ##Warp is function to rotate image

In [50]:
cv.imwrite(r"D:\Data Science Program\AI\Image Augumented\rotate_img.jpg",rotate_img)
cv.imshow("Rotated Images", rotate_img) 
cv.waitKey(0)
cv.destroyAllWindows()

# Flipping Image

In [35]:
flip_vert = cv.flip(re_img, 0)
flip_hori = cv.flip(re_img, 1)

In [36]:
two_flip = np.hstack((flip_vert, flip_hori))

In [51]:
cv.imwrite(r"D:\Data Science Program\AI\Image Augumented\two_flip.jpg",two_flip)
cv.imshow("Flipped Images", two_flip) 
cv.waitKey(0)
cv.destroyAllWindows()

# Shearing the Image

In [38]:
shear_factor= 0.5

In [39]:
shear_mat = np.float32([[1, shear_factor,0],[0,1,0]])  # this function use to rotate one side

In [40]:
shear_mat

array([[1. , 0.5, 0. ],
       [0. , 1. , 0. ]], dtype=float32)

In [41]:
sheared_img = cv.warpAffine(re_img, shear_mat, (cols + int(shear_factor*rows),rows))

In [52]:
cv.imwrite(r"D:\Data Science Program\AI\Image Augumented\sheared_img.jpg",sheared_img)
cv.imshow("Skewed Image", sheared_img) 
cv.waitKey(0)
cv.destroyAllWindows()